apiVersion: apps/v1
kind: Deployment

metadata:
  name: node-devops-deployment

spec:
  replicas: 2

  selector:
    matchLabels:
      app: node-devops

  template:
    metadata:
      labels:
        app: node-devops

    spec:
      containers:
      - name: node-devops
        image: jagadeesh1102/node-devops-project:latest
        imagePullPolicy: Always

        ports:
        - containerPort: 3000

        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"